apiVersion: v1
kind: Secret
metadata:
  name: gkzy-secret
  namespace: ns-gk5k0f3z
type: Opaque
stringData:
  # ⚠️ 部署前请修改以下值！
  DB_USERNAME: "root"
  DB_PASSWORD: "2qq52b8g"
  JWT_SECRET: "gkzy-prod-k8s-secret-2026-gaokao-zhiyuan-make-it-very-long-64-chars!"
